-- Monotonic sequence for a robust, URL-safe polling cursor (timestamps with
-- '+00' break when a query string decodes '+' to a space).
alter table public.support_messages
  add column if not exists seq bigint generated by default as identity;

create index if not exists support_messages_ticket_seq_idx
  on public.support_messages (ticket_id, seq);
